In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

import lightgbm as lgb

In [2]:
featureData = pd.read_csv("data.csv")

In [3]:
featureData

Unnamed: 0  k__Viruses.f__Phycodnaviridae.g__Prasinovirus  \
0       s12859                                              0   
1       s12878                                              0   
2       s12857                                              2   
3       s12882                                              4   
4       s12871                                              2   
..         ...                                            ...   
350      s3971                                              2   
351      s3942                                              4   
352      s3975                                              2   
353      s3926                                              0   
354      s3952                                              6   

     k__Viruses.o__Caudovirales.f__Siphoviridae.g__Sfi1unalikevirus  \
0                                                    0                
1                                                    0                
2                                                    0                
3                                                    0                
4                                                    0                
..                                                 ...                
350                                                  0                
351                                                  0                
352                                                  0                
353                                                  0                
354                                                  0                

     k__Viruses.o__Herpesvirales.f__Herpesviridae.g__Simplexvirus  \
0                                                   14              
1                                                   18              
2                                                  484              
3                                                   96              
4                                                  128              
..                                                 ...              
350                                                 36              
351                                                110              
352                                                 46              
353                                                118              
354                                                 94              

     k__Viruses.o__Caudovirales.f__Siphoviridae.g__C2likevirus  \
0                                                    0           
1                                                    0           
2                                                    0           
3                                                    0           
4                                                    0           
..                                                 ...           
350                                                  0           
351                                                  0           
352                                                  0           
353                                                  0           
354                                                  0           

     k__Viruses.f__Poxviridae.g__Parapoxvirus  \
0                                           0   
1                                           0   
2                                           8   
3                                           2   
4                                          16   
..                                        ...   
350                                         0   
351                                         0   
352                                         2   
353                                         2   
354                                         0   

     k__Viruses.f__Papillomaviridae.g__Dyolambdapapillomavirus  \
0                                                    0           
1                          

In [4]:
labelData = pd.read_csv("labels.csv")

In [5]:
labelData

Sample      disease_type
0    s12859      colon cancer
1    s12878      colon cancer
2    s12857      colon cancer
3    s12882      colon cancer
4    s12871      colon cancer
..      ...               ...
350   s3971  prosrtate cancer
351   s3942  prosrtate cancer
352   s3975  prosrtate cancer
353   s3926  prosrtate cancer
354   s3952  prosrtate cancer

[355 rows x 2 columns]

In [6]:
features = featureData[featureData.columns[1:]].values
labels = labelData[labelData.columns[1]].values

In [7]:
features

array([[  0,   0,  14, ...,   0,   0,   0],
       [  0,   0,  18, ...,   0,   0,   0],
       [  2,   0, 484, ...,   0,   0,   0],
       ...,
       [  2,   0,  46, ...,   0,   0,   0],
       [  0,   0, 118, ...,   0,   0,   0],
       [  6,   0,  94, ...,   0,   0,   0]])

In [8]:
labels

array(['colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'colon cancer', 'colon cancer',
      

In [9]:
featuresTrain, featuresTest, labelsTrain, labelsTest = train_test_split(features, labels, test_size=0.4, random_state=7)

In [10]:
labelsTrain

array(['prosrtate cancer', 'breast cancer', 'colon cancer',
       'colon cancer', 'colon cancer', 'prosrtate cancer', 'colon cancer',
       'prosrtate cancer', 'breast cancer', 'prosrtate cancer',
       'breast cancer', 'colon cancer', 'breast cancer',
       'prosrtate cancer', 'breast cancer', 'breast cancer',
       'colon cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'prosrtate cancer', 'colon cancer',
       'breast cancer', 'colon cancer', 'prosrtate cancer',
       'colon cancer', 'colon cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'colon cancer',
       'breast cancer', 'colon cancer', 'colon cancer', 'breast cancer',
       'breast cancer', 'colon cancer', 'colon cancer', 'breast cancer',
       'prosrtate cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'prosrtate cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'prosrtate cancer', 'breast cancer',
       'colon cancer', 'br

In [11]:
labelsTest

array(['breast cancer', 'colon cancer', 'prosrtate cancer',
       'colon cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'colon cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'breast cancer',
       'colon cancer', 'colon cancer', 'prosrtate cancer',
       'breast cancer', 'breast cancer', 'breast cancer',
       'prosrtate cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'prosrtate cancer', 'breast cancer', 'colon cancer',
       'colon cancer', 'prosrtate cancer', 'lung cancer',
       'prosrtate cancer', 'colon cancer', 'prosrtate cancer',
       'colon cancer', 'prosrtate cancer', 'lung cancer',
       'prosrtate cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'prosrtate cancer',
       'prosrtate cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'breast cancer',
       'breast cancer', 'prosrtate cancer', 'prosrtate cancer',

In [12]:
# Create a Random Forest classifier with 100 trees
rf_classifier = RandomForestClassifier(n_estimators=100)

# Train the classifier
rf_classifier.fit(featuresTrain, labelsTrain)

RandomForestClassifier()

In [13]:
clf = lgb.LGBMClassifier()


clf.fit(featuresTrain, labelsTrain)

LGBMClassifier()

In [14]:
# Predict the classes for the test dataset
predictedLabelsForest = rf_classifier.predict(featuresTest)
predictedLabelsForest

array(['breast cancer', 'colon cancer', 'prosrtate cancer',
       'colon cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'colon cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'breast cancer',
       'colon cancer', 'colon cancer', 'prosrtate cancer',
       'breast cancer', 'breast cancer', 'breast cancer',
       'prosrtate cancer', 'prosrtate cancer', 'colon cancer',
       'colon cancer', 'prosrtate cancer', 'breast cancer',
       'colon cancer', 'colon cancer', 'prosrtate cancer', 'lung cancer',
       'prosrtate cancer', 'colon cancer', 'prosrtate cancer',
       'colon cancer', 'prosrtate cancer', 'lung cancer',
       'prosrtate cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'prosrtate cancer',
       'prosrtate cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'breast cancer',
       'breast cancer', 'prosrtate cancer', 'prosrtate canc

In [15]:
predictedLabelsForest.shape

(142,)

In [16]:
predictedLabelsBoosted = clf.predict(featuresTest)
predictedLabelsBoosted

array(['breast cancer', 'colon cancer', 'prosrtate cancer',
       'colon cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'colon cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'breast cancer',
       'colon cancer', 'colon cancer', 'prosrtate cancer',
       'breast cancer', 'breast cancer', 'breast cancer',
       'prosrtate cancer', 'colon cancer', 'colon cancer', 'colon cancer',
       'prosrtate cancer', 'breast cancer', 'colon cancer',
       'colon cancer', 'prosrtate cancer', 'lung cancer',
       'prosrtate cancer', 'colon cancer', 'prosrtate cancer',
       'colon cancer', 'prosrtate cancer', 'lung cancer',
       'prosrtate cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'prosrtate cancer',
       'prosrtate cancer', 'prosrtate cancer', 'prosrtate cancer',
       'prosrtate cancer', 'breast cancer', 'breast cancer',
       'breast cancer', 'prosrtate cancer', 'prosrtate cancer',

In [17]:
predictedLabelsBoosted.shape

(142,)

In [18]:
# Calculate the confusion matrix
confusion_mat = confusion_matrix(labelsTest, predictedLabelsForest)
confusion_mat

array([[37,  0,  0,  1],
       [ 0, 42,  0,  1],
       [ 0,  0,  8,  0],
       [ 0,  0,  1, 52]])

In [19]:
# Extract the values from the confusion matrix
true_positives = confusion_mat.diagonal()
false_negatives = confusion_mat.sum(axis=1) - true_positives
false_positives = confusion_mat.sum(axis=0) - true_positives
true_negatives = confusion_mat.sum() - (true_positives + false_negatives + false_positives)

# Calculate sensitivity and specificity
sensitivity = np.mean(true_positives / (true_positives + false_negatives))
specificity = np.mean(true_negatives / (true_negatives + false_positives))

accuracy = np.sum(predictedLabelsForest == labelsTest) / len(labelsTest)

# Print the sensitivity and specificity
print("Random Forest Performance Measures")
print("----------------------------------")
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)
print("Accuracy:", accuracy)

Random Forest Performance Measures
----------------------------------
Sensitivity: 0.9828901180111314
Specificity: 0.992516350830119
Accuracy: 0.9788732394366197


In [20]:
confusion_mat = confusion_matrix(labelsTest, predictedLabelsBoosted)
confusion_mat

array([[38,  0,  0,  0],
       [ 0, 43,  0,  0],
       [ 0,  0,  7,  1],
       [ 0,  0,  1, 52]])

In [21]:
true_positives = confusion_mat.diagonal()
false_negatives = confusion_mat.sum(axis=1) - true_positives
false_positives = confusion_mat.sum(axis=0) - true_positives
true_negatives = confusion_mat.sum() - (true_positives + false_negatives + false_positives)

# Calculate sensitivity and specificity
sensitivity = np.mean(true_positives / (true_positives + false_negatives))
specificity = np.mean(true_negatives / (true_negatives + false_positives))

accuracy = np.sum(predictedLabelsBoosted == labelsTest) / len(labelsTest)

# Print the sensitivity and specificity
print("Boosted Gradient Tree Performance Measures")
print("----------------------------------")
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)
print("Accuracy:", accuracy)

Boosted Gradient Tree Performance Measures
----------------------------------
Sensitivity: 0.9640330188679245
Specificity: 0.9953253395941639
Accuracy: 0.9859154929577465
